"""initial

Revision ID: 01773abb6cf1
Revises:
Create Date: 2026-08-03 16:05:36.232002

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01773abb6cf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('errata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('advisory_id', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('usn', 'dsa', name='erratum_source'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('cves', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advisory_id')
    )
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('archive_url', sa.String(), nullable=False),
    sa.Column('distribution', sa.String(), nullable=False),
    sa.Column('components', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('architectures', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('create_user', 'create_repository', 'sync_repository', 'cut_snapshot', 'publish_content_view', 'switch_publish', 'rollback_environment', 'create_content_view', 'create_content_view_filter', 'create_lifecycle_environment', 'create_server', 'trigger_bootstrap', 'trigger_apply_updates', 'trigger_gather_facts', 'create_host_group', 'update_host_group_membership', 'create_activation_key', 'revoke_activation_key', 'register_via_activation_key', 'trigger_bulk_apply_updates', 'trigger_run_command', 'trigger_manage_package', 'decommission_server', 'mark_server_unreachable', 'flag_stale_server', 'create_site', 'create_relay', 'update_site_environments', 'assign_server_site', 'login', 'login_failed', 'export_audit_log', name='audit_action'), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_view_filters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_view_id', sa.UUID(), nullable=False),
    sa.Column('filter_type', sa.Enum('include', 'exclude', 'errata_since', name='filter_type'), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_view_id'], ['content_views.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_view_repositories',
    sa.Column('content_view_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_view_id'], ['content_views.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('content_view_id', 'repository_id')
    )
    op.create_table('content_view_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_view_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshots', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['content_view_id'], ['content_views.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_view_id', 'version')
    )
    op.create_table('erratum_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('erratum_id', sa.UUID(), nullable=False),
    sa.Column('release', sa.String(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('fixed_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['erratum_id'], ['errata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_erratum_packages_package_name', 'erratum_packages', ['package_name'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('relays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ssh_user', sa.String(), nullable=False),
    sa.Column('sync_status', sa.Enum('never_synced', 'healthy', 'stale', 'failed', name='relay_sync_status'), nullable=False),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id')
    )
    op.create_table('lifecycle_environments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path_name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content_view_id', sa.UUID(), nullable=False),
    sa.Column('distro', sa.String(), nullable=False),
    sa.Column('release', sa.String(), nullable=False),
    sa.Column('publish_prefix', sa.String(), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('gpg_key_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_view_id'], ['content_views.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['content_view_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('path_name', 'position'),
    sa.UniqueConstraint('publish_prefix')
    )
    op.create_table('host_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_environment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_environment_id'], ['lifecycle_environments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('site_environments',
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['lifecycle_environments.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('site_id', 'environment_id')
    )
    op.create_table('activation_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('host_group_id', sa.UUID(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['lifecycle_environments.id'], ),
    sa.ForeignKeyConstraint(['host_group_id'], ['host_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('ssh_user', sa.String(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('registered', 'bootstrapped', 'unreachable', name='server_status'), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('active', 'decommissioned', name='server_lifecycle_state'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_via_activation_key_id', sa.UUID(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('ssh_key_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['lifecycle_environments.id'], ),
    sa.ForeignKeyConstraint(['registered_via_activation_key_id'], ['activation_keys.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_check_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('drift', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('installed_packages', sa.JSON(), nullable=False),
    sa.Column('gathered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host_group_servers',
    sa.Column('host_group_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_group_id'], ['host_groups.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('host_group_id', 'server_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('bootstrap', 'apply_updates', 'gather_facts', 'bulk_apply_updates', 'run_command', 'manage_package', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='job_status'), nullable=False),
    sa.Column('target_type', sa.Enum('server', 'environment', 'host_group', 'adhoc', name='job_target_type'), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=True),
    sa.Column('environment_id', sa.UUID(), nullable=True),
    sa.Column('host_group_id', sa.UUID(), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['lifecycle_environments.id'], ),
    sa.ForeignKeyConstraint(['host_group_id'], ['host_groups.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('os_distribution', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('kernel', sa.String(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('disk', sa.JSON(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('gathered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_server_facts_server_id_gathered_at', 'server_facts', ['server_id', 'gathered_at'], unique=False)
    op.create_table('job_servers',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'server_id')
    )
    op.create_index('ix_job_servers_server_id', 'job_servers', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_servers_server_id', table_name='job_servers')
    op.drop_table('job_servers')
    op.drop_index('ix_server_facts_server_id_gathered_at', table_name='server_facts')
    op.drop_table('server_facts')
    op.drop_table('jobs')
    op.drop_table('host_group_servers')
    op.drop_table('compliance_records')
    op.drop_table('compliance_check_logs')
    op.drop_table('servers')
    op.drop_table('activation_keys')
    op.drop_table('site_environments')
    op.drop_table('host_groups')
    op.drop_table('lifecycle_environments')
    op.drop_table('relays')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_erratum_packages_package_name', table_name='erratum_packages')
    op.drop_table('erratum_packages')
    op.drop_table('content_view_versions')
    op.drop_table('content_view_repositories')
    op.drop_table('content_view_filters')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('sites')
    op.drop_table('repositories')
    op.drop_table('errata')
    op.drop_table('content_views')
    # ### end Alembic commands ###
